# Site settings
title: Arun Marria's CV 
description: arunmarria's CV
favicon: /assets/img/avatar.JPG
baseurl: https://arunmarria.github.io/resumecard
url: https://arunmarria.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Arun Marria
  title: UBC MDS student
  address: Vancouver, Canada
  email: abc@gmail.com
  link: 
  weibo:
  github: arunmarria
  linkedin: 
  twitter: 
  gavatar: 
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: SAP
      location: Vancouver, Canada 
      title: Database Consultant
      started: 2016
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: UBC
      location: Vancouver, Canada
      degree: Bachelor
      major: Electtical Engineering
      started: 2009
      duration: (2009-2016)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: English
      proficiency: Professional
    - language2:
      name: Hindi
      proficiency: Native
    - language3:
      name: Punjabi
      proficiency: Native
  programmingSkills:
    - skill1:
      name: Python
      percentage: 100%
    - skill2:
      name: R
      percentage: 70%
    - skill3:
      name: SQL
      percentage: 100%
    - skill4:
      name: Java
      percentage: 70%
    - skill5:
      name: Embedded C
      percentage: 70%
